name: CI
on:

  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
          
      - name: listando arquivos.
        run: ls
      
      - name: Instalando dependencias.
        run: dotnet restore

      - name: build.
        run: dotnet build
        
      - name: Rodando os testes.
        run: dotnet test
        
      - name: listando arquivos.
        run: ls 

      - name: navegando
        run: cd Encurtador-Urls && ls
        
      - name: Upload de Artefato
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/artifact/ # or path/to/artifact
          
      - name: Download de Artefato 
        uses: actions/download-artifact@v4
        with:
          name: meu-artefato
          
      - name: exibindo a estrutura dos arquivos baixados
        run: ls


            
