name: Deploy
on: [push]

jobs:
  deploy_ubuntu:
    name: Deploy to Ubuntu Oracle
    runs-on: ubuntu-latest

    steps:
    - name: "Baixar codigo"
      uses: actions/checkout@v4

    - name: copiando via SSH
      uses: appleboy/scp-action@0.1.7
      with:
        host: ${{ secrets.DEPLOY_SSH_HOST }}
        username: ${{ secrets.DEPLOY_SSH_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        source: "."
        target: "/teste"
