name: Deploy
on: [push]

jobs:
  deploy_ubuntu:
    name: Deploy to Ubuntu Oracle
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/deploy.key
        chmod 600 ~/.ssh/deploy.key
        cat >>~/.ssh/config <<END
        Host batata
          HostName ${{ secrets.DEPLOY_SSH_HOST }}
          User ${{ secrets.DEPLOY_SSH_USER }}
          IdentityFile ~/.ssh/deploy.key
          StrictHostKeyChecking no
        END
      env:
        SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Send files
      run: "rsync --delete -avO ${{ env.RSYNC_FLAGS }} ./ ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.DESTINATION }}"
      env:
        RSYNC_FLAGS: '' #--dry-run
        SSH_USER: ${{ secrets.DEPLOY_SSH_USER }}
        SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
        DESTINATION: "~/teste"
